version: '3'

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      HOST_EMAIL: ${HOST_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      EMAIL_TEMPLATE_PATH: ${EMAIL_TEMPLATE_PATH}
    networks:
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /c/Users/Personal/docker-data/postgresql:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
